/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthenticationRequest } from './models/authentication-request';
export { AuthenticationResponse } from './models/authentication-response';
export { FeedbackRequest } from './models/feedback-request';
export { FeedbackResponse } from './models/feedback-response';
export { MovieRequest } from './models/movie-request';
export { MovieResponse } from './models/movie-response';
export { PageResponseFeedbackResponse } from './models/page-response-feedback-response';
export { PageResponseMovieResponse } from './models/page-response-movie-response';
export { RegistrationRequest } from './models/registration-request';
