/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { MovieControllerService } from './services/movie-controller.service';
export { FeedbackControllerService } from './services/feedback-controller.service';
export { AuthenticationControllerService } from './services/authentication-controller.service';
