/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthenticationResponse {
  email?: string;
  fullname?: string;
  role?: string;
  token?: string;
}
