/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MovieResponse {
  id?: number;
  poster?: string;
  rate?: number;
  released?: string;
  title?: string;
}
