/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MovieRequest {
  Released: string;
  id?: number;
  posterUrl: string;
  title: string;
  year: string;
}
